import React from 'react';

export const metadata = {
  title: "Fuji's Blog",
  description: 'Generated by create next app',
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
